version: "3.7"
services:
  app:
    build: .
    command: "python app.py"
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    volumes: 
      - .:/app
  worker:
    build:
      context: .
    command: celery -A tasks worker -l info -E
    depends_on:
      - rabbit
    volumes: 
      - .:/app
    links:
      - rabbit
  
  rabbit:
    image: rabbitmq:3
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5673:5672"
      - "15672:15672"